global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'helios-node-1'
    static_configs:
      - targets: ['192.168.1.2:26660']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'helios-node-2'
    static_configs:
      - targets: ['192.168.1.3:26660']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'helios-node-3'
    static_configs:
      - targets: ['192.168.1.4:26660']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'helios-node-4'
    static_configs:
      - targets: ['192.168.1.5:26660']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'helios-node-5'
    static_configs:
      - targets: ['192.168.1.6:26660']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'helios-api-1'
    static_configs:
      - targets: ['192.168.1.2:1317']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'helios-api-2'
    static_configs:
      - targets: ['192.168.1.3:1317']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'helios-api-3'
    static_configs:
      - targets: ['192.168.1.4:1317']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'helios-api-4'
    static_configs:
      - targets: ['192.168.1.5:1317']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'helios-api-5'
    static_configs:
      - targets: ['192.168.1.6:1317']
    metrics_path: /metrics
    scrape_interval: 15s 